### ISSUE TITLE
Token de validação da JWT exposto no código fonte

### ISSUE THREAD

**Issue by willianrschuck** [DarlanNoetzold/spyware-API#1]
Na linha 25 do arquivo [JWTAutenticarFilter.java](https://github.com/DarlanNoetzold/spyware-API/blob/e0161c8966825312e430756e010baa6016b04067/src/main/java/tech/noetzold/spyware/security/JWTAutenticarFilter.java) está pública a string utilizada para a assinatura e validação dos tokens.
É possível através dessa informação gerar um JWT e se autenticar com a api sem mesmo ter um usuário cadastrado.

**Comment by DarlanNoetzold** [comment]
Opa, tinha me esquecido de esconder isso por que ainda tava em fase de
testes. Valeu por avisar. Já está resolvido!


Em sáb., 21 de mai. de 2022 às 10:52, Willian Schuck <
***@***.***> escreveu:
